# Generated by Django 5.2.4 on 2025-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.BigIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
