version: '3.9'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - smtp4dev
    env_file:
      - .env

  celery-worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - smtp4dev
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - smtp4dev
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  smtp:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "8025:80"    # Web UI
      - "1025:25"    # SMTP Port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 30s
      retries: 3
    restart: unless-stopped