# Generated by Django 5.2.4 on 2025-07-21 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('dead_line', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, default='todo_photos', null=True, upload_to='todo_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
                ('watcher', models.ForeignKey(blank=True, help_text='A friends or a family member can watch you do your todo and approve!', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watching_todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
